### ISSUE TITLE
Feedback preference-v7 BUG

### ISSUE THREAD

**Issue by TCQQ** [Gericop/Android-Support-Preference-V7-Fix#113]
if use "ColorPickerPreference", preview interface cannot be displayed

![image](https://user-images.githubusercontent.com/10644057/32997278-8d2eeb38-cdc8-11e7-9546-25c040d48a6b.png)

![image](https://user-images.githubusercontent.com/10644057/32997279-948ca668-cdc8-11e7-82bc-1e8933a92fdd.png)

**Comment by Gericop** [comment]
It's pretty much possible because this lib uses certain classes not available at design-time and the built-in designer does not know about these classes that are required (and available) at run-time, hence it cannot display the preview.

**Comment by TCQQ** [comment]
How can make it previewable?

**Comment by Gericop** [comment]
Run it on a device / emulator. You can also replace the custom preferences (e.g. `ColorPickerPreference`) in your XML with a standard one, like `EditTextPreference` and preview it like that. I'd recommend the former though because replacing and re-replacing preferences can be overwhelming and prone to bugs.

**Comment by TCQQ** [comment]
Well, if can preview in the android studio preview interface is the best
