### ISSUE TITLE
Feedback preference-v7 the layout problem

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#114]
The layout does not match the material design

https://material.io/guidelines/patterns/settings.html#settings-usage

![image](https://user-images.githubusercontent.com/10644057/32997389-73db69f2-cdca-11e7-928b-d4e248019c7f.png)
![image](https://user-images.githubusercontent.com/10644057/32997412-c4f62d0e-cdca-11e7-8e5e-89ea14fecacf.png)

**Comment by Gericop** [comment]
What does not match exactly? If you set an icon to the `SeekBarPreference` it will have the left "padding", and don't use the value showing one, then you won't have the value there.

**Comment by TCQQ** [comment]
![image](https://user-images.githubusercontent.com/10644057/33189086-82c522e2-d0da-11e7-81fb-5f58232ed386.png)
![image](https://user-images.githubusercontent.com/10644057/33189089-8d0f86ca-d0da-11e7-879b-a47fd237667b.png)
Please compare two pictures red box

![image](https://user-images.githubusercontent.com/10644057/33189091-91c537c8-d0da-11e7-809e-6872d0bc0c51.png)

**Comment by TCQQ** [comment]
The blue frame area is margin, so the progress value can be placed in the red frame position
![image](https://user-images.githubusercontent.com/10644057/33189186-6f595006-d0db-11e7-802a-6e79639d3daf.png)

![image](https://user-images.githubusercontent.com/10644057/33189251-f126638a-d0db-11e7-9a98-2278e8cbe8a4.png)

**Comment by Gericop** [comment]
There's no example with a displayed value so it cannot be told where it should go, and hard to find where the margin should be, since it pretty much seems random. The left side of the seek bar is aligned with the title but the right side has a bit more padding than where the widget margin goes (look at the switch below the seek bar). Also, there's not a single example without the big padding on the left (the "preserved icon space").

Where did you get this picture from? If you check the position of the _A_ character in "Alarm" and "Also", they are not aligned. (And this pic differs from the example in the material guidelines.)

**Comment by TCQQ** [comment]
“There's no example with a displayed value so it cannot be told where it should go, and hard to find where the margin should be, since it pretty much seems random. ”

-Yes, but the right end of "SeekBar" in the material design example is aligned with the end of the right title bar icon:
![image](https://user-images.githubusercontent.com/10644057/33190275-f5e9b084-d0e5-11e7-9f24-c48fb947fb5a.png)
Not like this:
![image](https://user-images.githubusercontent.com/10644057/33190302-40f930ea-d0e6-11e7-8a14-b2eb44d5d4e5.png)

So if added displayed value, put in the red frame position is the best typesetting
![image](https://user-images.githubusercontent.com/10644057/33190333-869acec4-d0e6-11e7-86e4-fa3fbc300562.png)

**Comment by TCQQ** [comment]
“Also, there's not a single example without the big padding on the left (the "preserved icon space").”

-Compare two pictures
![image](https://user-images.githubusercontent.com/10644057/33190412-6bbe5174-d0e7-11e7-8223-a6b953013899.png)
![image](https://user-images.githubusercontent.com/10644057/33190417-7618962a-d0e7-11e7-9b57-285c3af3a857.png)

https://material.io/guidelines/patterns/settings.html#settings-usage

**Comment by TCQQ** [comment]
“Where did you get this picture from? If you check the position of the A character in "Alarm" and "Also", they are not aligned. (And this pic differs from the example in the material guidelines.)”

This picture is from google pixel phone, it is the same material design

![image](https://user-images.githubusercontent.com/10644057/33190476-144bb1d8-d0e8-11e7-8151-fa595c7da2c9.png)
![image](https://user-images.githubusercontent.com/10644057/33190485-302f4996-d0e8-11e7-895c-f9bd193909b2.png)

**Comment by Gericop** [comment]
This is your phone then (just to show you what Google did...):
![mat_align](https://user-images.githubusercontent.com/5181621/33190754-9b02a836-d0b0-11e7-9500-1dd80f1915d9.png)

---

The other thing is what I said: the material guideline has no example without the preserved icon space (what you marked with the red rectangle):
![icon_preserved](https://user-images.githubusercontent.com/10644057/33190412-6bbe5174-d0e7-11e7-8223-a6b953013899.png)

All of them contain this space even though there are no icons around. This can be enabled in the XML though with `app:iconSpaceReserved="true"` if you need it, but the problem is that it's pretty hard to align anything without a proper example.

---

What I'm trying to say is that you can clearly see that the material guideline was made using some graphics software and even Google didn't implement it pixel-perfect on their own device. Also, it's a "guideline", so not some strict set of rules (and there's no layout image either with the different distances defined clearly; this settings page is about the UX not the UI).

**Comment by TCQQ** [comment]
Um, but anyway, now the displayed  value the layout the position is not appropriate 

![image](https://user-images.githubusercontent.com/10644057/33191081-1636c5f2-d0f0-11e7-946b-b41341683404.png)
