### ISSUE TITLE
Feedback “SwitchPreferenceCompat” problem

### ISSUE THREAD

**Issue by tcqq** [Gericop/Android-Support-Preference-V7-Fix#130]
How to programmatically change "SwitchPreferenceCompat" color? this is useful for customizable themes apps
![image](https://user-images.githubusercontent.com/10644057/33795982-a8a67080-dd26-11e7-90a8-302cffd06e99.png)

**Comment by Gericop** [comment]
The `SwitchPreferenceCompat` uses the accent color (just like every other widget) to tint its UI.

I think your approach to a customizable theme app is generally bad since you allow the user to select an _arbitrary_ color which means that you need to programmatically tint every single widget and view in the UI. Beside this being cumbersome and error prone from your point of view (since you can easily forget to tint a widget), you cannot control the generic appearance of the app. A better approach (IMO) would be to provide a fix set of colors (say, 20 of them) and create the styles for them beforehand. Check out [this](https://stackoverflow.com/a/37905131) StackOverflow answer for more details.

**Comment by TCQQ** [comment]
“I think your approach to a customizable theme app is generally bad ”

-No, this will make the user experience more humane, empathy, and if you are a user of this app, I believe you also prefer to support applications that change the subject to myself favorite color.

"since you allow the user to select an arbitrary color which means that you need to programmatically tint every single widget and view in the UI. "

-Yes, but I will encapsulation to repeat the code code, so it which is as easy as setting the color in xml.
![image](https://user-images.githubusercontent.com/10644057/33848822-d4c263f8-dee9-11e7-90f9-dd2342d62e94.png)
![image](https://user-images.githubusercontent.com/10644057/33849159-c2afe82e-deea-11e7-8554-e79e373a5d84.png)
![image](https://user-images.githubusercontent.com/10644057/33849309-3b9acaa6-deeb-11e7-9227-b22d74c894c4.png)

"Beside this being cumbersome and error prone"

-Encapsulation process trouble, but the use of the process and xml as simple

"from your point of view (since you can easily forget to tint a widget), you cannot control the generic appearance of the app."

- No, because the widget's color has only two cases: primary color or accent color, at the same time, I encapsulated the code and added comments, so i can control the generic appearance of the app. 


"A better approach (IMO) would be to provide a fix set of colors (say, 20 of them) and create the styles for them beforehand. Check out this StackOverflow answer for more details."

-Yes, this is actually hard coded primary color and accent color, but in future  if app have more and more users because different users like the color is not the same, so I need to use hard-coding to add more primary color and accent color to meet the user, so this means that the future will face a greater workload

**Comment by Gericop** [comment]
You basically just want every preference type to be customizable. This is not going to happen and there are multiple reasons for that:
- it's uncommon to change primary and accent colors dynamically so it would mean a bigger lib size for a lot of devs who wouldn't want to use this feature
- it requires significantly more time to maintain the code base because every single preference type should inherit from a custom `Preference` base class that provides the (abstract) setter methods and those methods need to be implemented by every preference type so that they can override the colors of the widgets and whatnot
- it's impossible to change the color of the radio button in an `AlertDialog` (`ListPreference` uses it for example)

If I were you, I'd try the following. Create a screen where (in portrait mode) the most of the upper part (say, 2/3 of the screen) is a "sample" view which displays a sample of one of the screens of the applications itself. Below that would be the controls for setting the appropriate colors. Whenever the user changes those, just update the sample view accordingly. This way the rest of the settings screen would be just light or dark themed with predefined primary / accent colors, but the sample screen would show the user what the rest of the app will look like.

**Comment by tcqq** [comment]
I think your right.
