### ISSUE TITLE
How to import preference-v7 modules

### ISSUE THREAD

**Issue by mik61** [Gericop/Android-Support-Preference-V7-Fix#157]
Hi there
Not sure if this is the place to ask for assistance but i'm having trouble importing your modules into Android Studio. I am new to Android and have been trying everything. But i cannot get it to appear in the Android Project window panel.

It seems that Android Studio will only allow AAR and JAR modules to be imported. 

I have also tried your lib references and recompiling the gradle. 

Also had no luck using Android Studio's Project Structure dialog. 

I am also using the latest Gradle v4.4 and your lib v27.1.1.1.

Hope someone can point me in the right direction.

Thanks
Mik

**Comment by Gericop** [comment]
You don't see the lib in your project window because you _shouldn't_. This is not part of your project _per se_ but merely an imported "thing". You can access the lib's content the same way you access anything else by importing the classes in your files like you do with other java classes.

Do you get any build errors when you add the necessary line to your gradle file?

**Comment by mik61** [comment]
Hi there
Thanks for your quick reply. Android Studio needs to know where your library classes are located. All the blogs i read refer to importing library modules. But Android Studio will only accept AAR of JAR files so i am at a loss what to do.

**Comment by Gericop** [comment]
I think you should read the guide on [how to configure your builds](https://developer.android.com/studio/build/). In a nutshell, you need to add the `implementation 'com.takisoft.fix:preference-v7:27.1.1.1'` line to your dependencies in your module's (probably the "app" named module's) gradle file.

**Comment by mik61** [comment]
Thanks for the excellent reference Gergely, just what i needed.

**Comment by mik61** [comment]
Hi there 
Read through most of the references you provided me thanks. I am now able to link to your modules  thanks to your instructions. But i still have issues compiling your modules. Attribute references between you modules don't get recognized.
I have set the following in my 'build.gradle (Module:app)
dependencies {
    ......
//    compile 'com.android.support:preference-v7:27.0.2'
    compile 'com.takisoft.fix:preference-v7:27.1.1.1'
    compile 'com.takisoft.fix:preference-v7-extras:27.1.1.1'
    compile 'com.takisoft.fix:preference-v7-ringtone:27.1.1.1'
    compile 'com.takisoft.fix:preference-v7-datetimepicker:27.1.1.1'
    compile 'com.takisoft.fix:preference-v7-colorpicker:27.1.1.1'
    compile 'com.takisoft.fix:preference-v7-simplemenu:27.1.1.1'
} 
When i try to compile (even tried cleaning project) i get the following errors
![img](https://user-images.githubusercontent.com/39235491/39999178-b9eb75dc-57cb-11e8-8603-00e9bc397e58.JPG)

**Comment by Gericop** [comment]
That is because you have to use the same version of the support libs. This preferences fix lib always follows this version name syntax: the first three numbers come from the official support lib version (so 27.1.1 as of now), and the last number is the lib's own version code so bugs can be fixed between official versions.

This means that you need to use the 27.1.1 version of the appcompat-v7 lib:

```gradle
implementation 'com.android.support:appcompat-v7:27.1.1'
```
