### ISSUE TITLE
Use of Semantic Versioning

### ISSUE THREAD

**Issue by haibison** [Gericop/Android-Support-Preference-V7-Fix#32]
Hi,

I can't find any official documentation from support libraries which indicates that they are using [Semantic Versioning]. However judging from past versions, I think they are.

So, from that base, it looks weird that you append a dot and then your version number to their original version. Would you please have a look at Semantic Versioning and try another scheme? For example, I think this one is good: `24.1.1-fix.1`, `24.1.1-fix.2`, `24.1.1-fix.3`...

My own library uses the pre-release section as the whole mirror of major-minor-patch. For example:

- `24.1.1-1.0.0`: first release.
- `24.1.1-1.0.1`: patches.
- `24.1.1-1.1.0`: added some features.
- ...

But that would become complicated. So it's up to you to choose. But it would be nice if you agree to adapting Semantic Versioning.

Thank you,

[Semantic Versioning]: http://semver.org/

**Comment by Gericop** [comment]
I don't see why the `-fix.1` suffix would make it better. Also, this project merely contains features, it's more of fixes for what the guys at Google couldn't (wouldn't...) do. Sometimes I add new features when people ask if this and that could be added and seems like more people would use it. Also, the versioning is really easy in this way because it's always the Google version + `.x`.

It's important to note (again) that this lib's main profile is the fix it gives for the bugs / annoying things one can found in the official support lib. I understand it looks *interesting* that there's a version of 23.4.0.**5** and there's the next one with 24.0.0.**0**, but the appended number really just means that there's the official Google version and if I find any errors in that, I'll (try to) fix them, so the last number is not the version of my lib but rather the iteration of the bugfixes on the lib it's applied on. I'm sorry if it looks weird or anything but you can still checkout the whole lib using git anytime and just use it as-is, without the version numbers.

**Comment by haibison** [comment]
Thank you,

It's not about `-fix.1` or `-1.0.0`... They are only suggestions.

My point is about Semantic Versioning, which helps a lot describing what your next version does (adding feature, fixing bugs...) Using some numbers to describe an update is better than a paragraph of sentences, in my view.

Thanks for your hard work.
