### ISSUE TITLE
Can't use Layout Creator with library

### ISSUE THREAD

**Issue by NovaViper** [Gericop/Android-Support-Preference-V7-Fix#74]
I've been having trouble using the library as it makes it impossible to drag-n-drop the elements from the menu, I can't change the theme of the layout either. The bug goes away when I switch the default library (without the back support)

**Comment by Gericop** [comment]
It's probably because the layout editor is designed for the framework implementation instead of the support one, so there's nothing I can do about it.
One workaround would be to create the desired layout in a different project and just copy the XML over. Note, however, that you cannot use certain preference types, such as `RingtonePreference`.

**Comment by NovaViper** [comment]
Awh.. I really find it useful to use AS's Layout designer. Do you have any recommendations for an alternative designer for Android?

**Comment by NovaViper** [comment]
Ah ha! I have discovered that it is MineTweaker/CraftTweaker!
https://gist.github.com/NovaViper/bf83517c4586866b815c302deb5cc7ab

I will send this issue over to the developers of CraftTweaker
