### ISSUE TITLE
Dialog buttons hidden behind keyboard

### ISSUE THREAD

**Issue by Pitel** [Gericop/Android-Support-Preference-V7-Fix#82]
On some phones, the `EditText` dialog has buttons hidden behind keyboard.

But normal dialogs in other apps moves away whe keyboard appears. Why not here?

**Comment by Gericop** [comment]
Could you show a screenshot? Can't reproduce it on my devices. However, I don't do anything with the dialog handling, so it's up to the base library, whatever happens with the displayed dialog.

**Comment by Pitel** [comment]
On Nexus 5X (Android 7.1), it actualy shrinks the part of dialog with `EditText`:

![device-2017-06-29-160346](https://user-images.githubusercontent.com/113248/27691576-b0dcb95c-5ce4-11e7-8e5d-97a058e8e5f7.png)

But on one fo my customer's phone with Android 4 or 5, the keyboard is above the dialog and the suggestions bar hides the dialog's buttons. Sorry, I can't get the screenshot at the moment.

Maybe this should be another issue your library fixes.

I found [this](https://stackoverflow.com/questions/16885300/dialogfragment-not-resizing-when-keyboard-shown) on Stack Overflow.

Maybe just add this to `onCreate()` of your dialog implementation:
```java
getDialog().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
```

**Comment by Gericop** [comment]
Still cannot reproduce. I tried it on 7.0 and 5.0.1 but the dialog works good: if the content is too high, it moves up til possible, the bottom part is not touching the keyboard area, and the content is scrolling. Otherwise the dialog displays normally with all its content and buttons visible. Do you have this problem with the sample app too? I think you set the `windowSoftInputMode` attribute (or something similar) on your `Activity` and it changes the behavior of the resizing methods.

**Comment by Gericop** [comment]
@Pitel Do you have this problem with the sample app too?

**Comment by little-fish** [comment]
I have the very same issue.
In my case, it was caused by
```<item name="android:windowTranslucentStatus">true</item>```

**Comment by ornolisvt** [comment]
Same issue, the problem is the same that report @little-fish

**Comment by gregkorossy** [comment]
@ornolisvt Is this present in v1.1.0?

**Comment by ornolisvt** [comment]
> @ornolisvt Is this present in v1.1.0?

I´m using Xamarin Android with Support libraries, not AndroidX libraries
